### ISSUE TITLE
Twitch instead of YouTube?

### ISSUE THREAD

**Issue by regisclandegre** [Koischizo/AI-Vtuber#15]
As a total coding noob (have absolutely no coding experience for Python), I got the EL TTS working and changed the voice ID for my EL and it sounds perfect. The responses are very "human-like" as well but the only thing is can I connect this to my Twitch channel instead of YouTube? Many thanks in advance!

**Comment by regisclandegre** [comment]
It's okay, I figured it out with the help of a friend.

**Comment by Adolfiux** [comment]
> It's okay, I figured it out with the help of a friend.

Could you share the code to do this, Im trying to use it on twitch? please!

**Comment by Sylensar** [comment]
I would liek to use it with Twitch also. Any help @regisclandegre ?
