### ISSUE TITLE
Error while installing requirements

### ISSUE THREAD

**Issue by SkorpionErosAI** [Koischizo/AI-Vtuber#18]
I get an error while trying to install the requirements, specifically with simpleaudio.

It says,
python setup.py bdist_wheel did not run successfully.
ERROR: Failed building wheel for simpleaudio

Sorry, I am new to this, if anyone knows what the problem is or knows what to do I would appreciate it very much, thank you.

**Comment by Adolfiux** [comment]
Same for me, voy a investigar sobre el tema y si encuentro algo vengo y lo publico aquí.

**Comment by Rygald** [comment]
Try: pip install simpleaudio --use-pep517

If error says "Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

Download it and run: pip install simpleaudio --use-pep517 again

**Comment by SkorpionErosAI** [comment]
> Try: pip install simpleaudio --use-pep517
> 
> If error says "Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"
> 
> Download it and run: pip install simpleaudio --use-pep517 again

Thank you very much, this worked.
