### ISSUE TITLE
How to add twitch chat?

### ISSUE THREAD

**Issue by SkorpionErosAI** [Koischizo/AI-Vtuber#28]
How would I go about adding twitch chat into the code? With the option to let the AI read both chats at the same time or for me to just decide which one it should read, would that be a possible thing to add to the code?

**Comment by meet447** [comment]
It would be possible u can use twitch token and api to implement chat system check yt there are many tutorial available

**Comment by Sylensar** [comment]
Did you figure it out?

**Comment by SkorpionErosAI** [comment]
yes I did one day later, like meet447 said, through yt tutorials

**Comment by Sylensar** [comment]
@SkorpionErosAI Can you point me to such vids?
