### ISSUE TITLE
ModuleNotFoundError: No module named 'pytchat'

### ISSUE THREAD

**Issue by nakumiayumu144** [Koischizo/AI-Vtuber#5]
I have installed pip install pytchat, but still like that
![image](https://user-images.githubusercontent.com/127565115/226154293-6dc35e55-b721-4928-8972-766e5eba803b.png)

**Comment by nakumiayumu144** [comment]
nvm I've fixed it

**Comment by KoroVT** [comment]
What did you do, im at the same error.

**Comment by nakumiayumu144** [comment]
> What did you do, im at the same error.

have you downloaded the module?
if not 
pip install pychat

**Comment by KoroVT** [comment]
yeah i already installed it thats why i find weird that is not detecting pytchat there :(

**Comment by nakumiayumu144** [comment]
maybe u need to add path

> yeah i already installed it thats why i find weird that is not detecting pytchat there :(
