### ISSUE TITLE
Eleven Labs Access Denied

### ISSUE THREAD

**Issue by Azkrom** [Koischizo/AI-Vtuber#6]
First thing, I gotta say this source is awesome, mad respect to you Shizo, but theres only an issue that I cant really find anything about it, basically the system works just fine with the default tts (without Eleven Labs pretty much), so I wanted to try it with the EL thing, it worked all fine, it gave the answer, but the answer did not play audio, and after some seconds, it throws up an error that basically says this: "PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpdrrn9z31.wav'", already tried some solutions I found to related issues about this, but none worked, and again, its an issue with playing Eleven Labs audio, the one with the default TTS works just fine, thank you for this still! Gotta wait for an answer :)

**Comment by Koischizo** [comment]
Have you installed `simpleaudio pyaudio ffmpeg` ? 

if not, do `pip install simpleaudio pyaudio ffmpeg`

if it still doesnt work, post the results of this
```
python -V
pip list simpleaudio pyaudio ffmpeg pydub
```

I got the same issue last time but managed to fix it with these missing dependencies.

**Comment by Azkrom** [comment]
Hey, sorry for the late answer, I already managed to fix it, it gave me an error when using your command about needing C+ 14 or greater, did some research and what fixed the issue to me was on this post:

https://stackoverflow.com/questions/52283840/i-cant-install-pyaudio-on-windows-how-to-solve-error-microsoft-visual-c-14

If anyone has tried `pip install simpleaudio pyaudio ffmpeg` and it doesnt work, you can also try to install it using this commands:
```
pip install pipwin
pipwin install pyaudio
```

This don't secure your issue will be fixed but it did fix mine, feeling like providing this fix in case someone else needs it.

Still thank you @Koischizo , you did help a lot, and I really have mad respect for you for open sourcing this, good luck, just gained a new sub! 👍
