### ISSUE TITLE
Is simpleaudio important?

### ISSUE THREAD

**Issue by Sayui1101** [Koischizo/AI-Vtuber#7]
So i try to run pip install -r requirements.txt and everthing is fine except simpleaudio, it said 
× Encountered error while trying to install package.
╰─> simpleaudio
simpleaudio is matters for this program or not. If yes, how do i fix it.
Thanks you and sorry for my poor english.

**Comment by yamada-sexta** [comment]
As far as I can tell, it’s not really that important.
You can try to run it without simpleaudio. 
if there is any issue you can post a follow up discussion.

**Comment by Sayui1101** [comment]
> As far as I can tell, it’s not really that important. You can try to run it without simpleaudio. if there is any issue you can post a follow up discussion.

It's work fine. Thanks you!
