### ISSUE TITLE
RuntimeWarning: Couldn't find ffmpeg or avconv

### ISSUE THREAD

**Issue by Willxx90** [Koischizo/AI-Vtuber#8]
Hey im getting this error:

C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

I have ffmpeg installed and don't know what to do.
Thank you!

**Comment by Lilia-ai** [comment]
Try adding the location of your ffmpeg bin directory to the Windows system path. Alternatively, you can place the Python script and config.json in the same folder as ffprobe.exe and ffmpeg.exe.

**Comment by Willxx90** [comment]
> Try adding the location of your ffmpeg bin directory to the Windows system path. Alternatively, you can place the Python script and config.json in the same folder as ffprobe.exe and ffmpeg.exe.

Hey,
worked thank you for the help!
